// Generated by CoffeeScript 1.3.3

var partialPath = nsqPath.loc;
var nsqPartialPath = partialPath + "index.html";

angular.module("myApp", ["myApp.filters", "myApp.services", "myApp.directives"]).config([
  "$routeProvider", function($routeProvider) {
    $routeProvider.when("/", {
      templateUrl: nsqPartialPath,
      controller: IndexCtrl
    });
    return $routeProvider.otherwise({
      redirectTo: "/"
    });
  }
]);
