// Generated by CoffeeScript 1.3.3
"use strict";

angular.module("myApp.filters", []).filter("interpolate", [
  "version", function(version) {
    return function(text) {
      return String(text).replace(/\%VERSION\%/g, version);
    };
  }
]);
