// Generated by CoffeeScript 1.3.3

angular.module('myApp.services', []).factory('PostModel', function($http, $q, Config) {
  var PostModel;
  PostModel = {
    modelPrefix: 'post',
    currentPage: 0,
    expiryTime: new Date("Fri Jun 22 2013 13:19:25 GMT-0400 (EDT)"),
    baseUrl: Config.apiDomain + 'v1/',
    paginationAmount: function() {
      return 15;
    },
    query: function(page, callback) {
      var storedData;
      console.log('PostModel#query');
      if (page == null) {
        page = PostModel.currentPage++;
      }
      console.log(page);
      storedData = sessionStorage.getItem(PostModel.modelPrefix + '_' + page);
      if (storedData && PostModel.expiryTime > new Date() && false) {
        return this.queryCache(page, callback);
      } else {
        return this.queryServer(page, callback);
      }
    },
    queryServer: function(page, callback) {
      var config;
      config = {
        method: 'JSONP',
        url: this.baseUrl + 'posts',
        params: {
          domain: Config.applicationDomain,
          start: page * PostModel.paginationAmount(),
          rows: PostModel.paginationAmount(),
          wt: 'json',
          'callback': 'JSON_CALLBACK'
        }
      };
      console.log('GET ' + config.url);
      console.log(config.params);
      return $http(config).success(function(data) {
        sessionStorage.setItem(PostModel.modelPrefix + '_' + page, JSON.stringify(data));
        if (data.expiryTime != null) {
          PostModel.expiryTime = data.expiryTime;
        }
        PostModel.processData(data);
        console.log(data);
        return callback(data);
      });
    },
    queryCache: function(page, callback) {
      var data;
      console.log('Post in cache.');
      data = JSON.parse(storedData);
      PostModel.processData(data);
      console.log(data);
      return callback(data);
    },
    search: function(query, callback) {
      var config;
      config = {
        method: 'JSONP',
        url: this.baseUrl + 'search',
        params: {
          domain: Config.applicationDomain,
          search: String(query).replace(/\?|=|&/g, ''),
          rows: '15',
          wt: 'json',
          'callback': 'JSON_CALLBACK'
        }
      };
      return $http(config).success(function(data) {
        PostModel.processData(data);
        console.log(data);
        return callback(data);
      });
    },
    processData: function(data) {
      var square, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        square = data[_i];
        _results.push(square['img'] = square['thumbnail'] || square['media'][0]);
      }
      return _results;
    }
  };
  return PostModel;
}).factory('Config', function() {
  var Config;
  Config = {
    applicationDomain: 'newsbloggingtoday.com',
    apiDomain: 'http://taleyarn.com/api/'
  };
  return Config;
});
