// Generated by CoffeeScript 1.3.3
var IndexCtrl;

IndexCtrl = function($scope, $http) {
  return $http.get("json/trendland.json").success(function(data) {
    return $scope.content = data;
  });
};

IndexCtrl.$inject = ["$scope", "$http"];
