// Generated by CoffeeScript 1.3.3
"use strict";

describe("my app", function() {
  beforeEach(function() {
    return browser().navigateTo("../../app/index.html");
  });
  return describe("Navigation View", function() {
    beforeEach(function() {
      return browser().navigateTo("#/");
    });
    it("should render the Navigation toolbar", function() {
      return expect(element(".toolbar").count()).toBeDefined();
    });
    it("should have categories", function() {
      return expect(element('li[ng-repeat="category in categories"]').count()).toBeGreaterThan(0);
    });
    return it("should have tags", function() {
      return expect(element('li[ng-repeat="tag in tags"]').count()).toBeGreaterThan(0);
    });
  });
});
